In [1]:
## Fooling around with NumPy basics

In [2]:
# imports
import numpy as np

In [3]:
# Single dimension
data1 = [1, 2, 3, 4, 5]
npdata1 = np.array(data1)
print(
    f'\nnpdata1 = {npdata1}'
    f'\nDimensions: {npdata1.ndim}'
    f'\nShape: {npdata1.shape}')


npdata1 = [1 2 3 4 5]
Dimensions: 1
Shape: (5,)


In [4]:
# Two or more dimensions
data2 = [[1, 2, 3], [4, 5, 6]]
npdata2 = np.array(data2)
print(
    f'\nnpdata2 = \n{npdata2}'
    f'\nDimensions: {npdata2.ndim}'
    f'\nShape: {npdata2.shape}')


npdata2 = 
[[1 2 3]
 [4 5 6]]
Dimensions: 2
Shape: (2, 3)


In [11]:
# Zeros, Ones and Empty
# np.empty brings trash with it
npzeros = np.zeros((5, 5))
print(f'\nnpzeros = \n{npzeros}')
npempty0 = np.empty((5,5))
print(f'\nnpempty0 = \n{npempty0}')
npones = np.ones((5,5))
print(f'\nnpones = \n{npones}')
npempty1 = np.empty((5,5))
print(f'\nnpempty1 = \n{npempty1}')

#  zeros_like, ones_like, etc
data = [[1,2,3],[4,5,6]]
print(f'\nExample data = {data}')
nponeslike = np.ones_like(data)
print(f'\nnponeslike based on data = \n{nponeslike}')
npzeroslike = np.zeros_like(data)
print(f'\nnpzeroslike based on data = \n{npzeroslike}')


npzeros = 
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]

npempty0 = 
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]

npones = 
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]

npempty1 = 
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]

Example data = [[1, 2, 3], [4, 5, 6]]

nponeslike based on data = 
[[1 1 1]
 [1 1 1]]

npzeroslike based on data = 
[[0 0 0]
 [0 0 0]]


In [6]:
# np.arange
nparange = np.arange(15)
print(f'\nnparange(15) = \n{nparange}')


nparange(15) = 
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [21]:
# np.astype -> convert dtype of an array
genericintdata = [[1,2,3],[4,5,6]]
genericfloatdata = [[1.3,2.1,3.0], [4.99,5.34,6.78]]
intarray = np.array(genericintdata, dtype=np.int32)
floatarray = np.array(genericfloatdata, dtype=np.float64)
print(
    f'intarray = \n{intarray}\n'
    f'\nfloatarray = \n{floatarray}')

# Type cast
print(
    f'\nintarray -> float64 = \n{intarray.astype(np.float64)}\n'
    f'\nfloatarray -> int32 = \n{floatarray.astype(np.int32)}')

intarray = 
[[1 2 3]
 [4 5 6]]

floatarray = 
[[1.3  2.1  3.  ]
 [4.99 5.34 6.78]]

intarray -> float64 = 
[[1. 2. 3.]
 [4. 5. 6.]]

floatarray -> int32 = 
[[1 2 3]
 [4 5 6]]


In [22]:
# Operations
arr = np.array([[1., 2., 3.], [4., 5., 6.]])
arr2 = np.array([[0., 4., 1.], [7., 2., 12.]])

In [24]:
# Scalar
arr * 10

array([[10., 20., 30.],
       [40., 50., 60.]])

In [25]:
# Itself
arr * arr

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [26]:
# Division scalar
1 / arr

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [27]:
# Comparison
arr < arr2

array([[False,  True, False],
       [ True, False,  True]])